AWSTemplateFormatVersion: '2010-09-09'
Description: Smart Photo Album Infrastructure 

# Parameters allow us to reuse this template. 
Parameters:
  ProjectName:
    Type: String
    Default: smart-album-cf-lkd8786
    Description: Base name for resources to ensure uniqueness

Resources:
  # --- 1. IAM ROLE ---
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      # We attach the AWS Managed Policies to save time writing custom JSON
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonRekognitionFullAccess
        - arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess

  # --- 2. S3 BUCKETS ---
  PhotosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-photos-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # The "Frontend" bucket (Website).
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-frontend-${AWS::AccountId}"
      WebsiteConfiguration:
        IndexDocument: index.html
      # CRITICAL: We explicitly turn OFF blocking so the website can be public.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # The Bucket Policy.

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"

  # --- 3. LAMBDA FUNCTIONS ---
  IndexPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-index-photos"
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps('Placeholder Code - Pipeline will update me!')}
      Runtime: python3.12
      Timeout: 30

  SearchPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-search-photos"
      Handler: search.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps('Placeholder Code - Pipeline will update me!')}
      Runtime: python3.12
      Timeout: 30

  # --- 4. API GATEWAY ---
  PhotoAlbumAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${ProjectName}-api"
      Description: API created by CloudFormation

# --- OUTPUTS ---
Outputs:
  FrontendURL:
    Value: !GetAtt FrontendBucket.WebsiteURL
    Description: The public URL of the frontend website
  ApiGatewayID:
    Value: !Ref PhotoAlbumAPI
    Description: The ID of the created API Gateway